inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - log/*
    - tmp/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Rails:
  Enabled: true
