inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
    - log/*
    - tmp/*

Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: native

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 130
  IgnoredPatterns: ['\A#']

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Rails:
  Enabled: true
