version: '3'
services:
  db:
    image: postgres:10.0
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    links:
      - db
    volumes:
      - .:/pup-pup-training-api
    ports:
      - "3001:3001"
    depends_on:
      - db
    stdin_open: true
    tty: true
  # bundle cache
  bundle:
    image: puppuptrainingapi_web
    volumes:
      - /bundle
