default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pup-pup-trainer-api_development

test:
  <<: *default
  database: pup-pup-trainer-api_test

production:
  <<: *default
  database: pup-pup-trainer-api_production
  username: pup-pup-trainer-api
  password: <%= ENV['PUP-PUP-TRAINER-API_DATABASE_PASSWORD'] %>
